// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMS.Data;

#nullable disable

namespace SMS.Data.Migrations
{
    [DbContext(typeof(SMSDbContext))]
    [Migration("20260920144304_Usergroup rightsId")]
    partial class UsergrouprightsId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMS.Data.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Activity_CreatorId");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Announcement_CreatorId");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("SMS.Data.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AttendanceRecord", (string)null);
                });

            modelBuilder.Entity("SMS.Data.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("AfterValue")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("BeforeValue")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AuditLog_UserId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassTeacherId" }, "IX_Class_ClassTeacherId");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Class_CreatorId");

                    b.HasIndex(new[] { "GradeId" }, "IX_Class_GradeId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Competition_CreatorId");

                    b.HasIndex(new[] { "TermId" }, "IX_Competition_TermId");

                    b.ToTable("Competition", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Code");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Currency_CreatorId");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("SMS.Data.FeesStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LevyTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_FeesStructure_CreatorId");

                    b.HasIndex(new[] { "CurrencyId" }, "IX_FeesStructure_CurrencyId");

                    b.ToTable("FeesStructure", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Grade_CreatorId");

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("VillageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Guardian_CreatorId");

                    b.ToTable("Guardian", (string)null);
                });

            modelBuilder.Entity("SMS.Data.House", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_House_CreatorId");

                    b.HasIndex(new[] { "MasterId" }, "IX_House_MasterId");

                    b.ToTable("House", (string)null);
                });

            modelBuilder.Entity("SMS.Data.LiturgicalDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Rank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LiturgicalDay", (string)null);
                });

            modelBuilder.Entity("SMS.Data.MassEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Celebrant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("LiturgicalDate")
                        .HasColumnType("date");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_MassEvent_CreatorId");

                    b.ToTable("MassEvent", (string)null);
                });

            modelBuilder.Entity("SMS.Data.MassRoster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MassId" }, "IX_MassRoster_MassId");

                    b.HasIndex(new[] { "StaffId" }, "IX_MassRoster_StaffId");

                    b.HasIndex(new[] { "StudentId" }, "IX_MassRoster_StudentId");

                    b.ToTable("MassRoster", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid?>("LedgerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("ProofOfPaymentUrl")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CurrencyId" }, "IX_Payment_CurrencyId");

                    b.HasIndex(new[] { "LedgerId" }, "IX_Payment_LedgerId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Prefect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("NominatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PostTitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Prefect_CreatorId");

                    b.HasIndex(new[] { "NominatorId" }, "IX_Prefect_NominatorId");

                    b.ToTable("Prefect", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BudgetAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ResponsiblePersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Project_CreatorId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("SMS.Data.ProjectMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PercentageComplete")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_ProjectMileStone");

                    b.HasIndex(new[] { "CreatorId" }, "IX_ProjectMilestone_CreatorId");

                    b.HasIndex(new[] { "ProjectId" }, "IX_ProjectMilestone_ProjectId");

                    b.ToTable("ProjectMilestone", (string)null);
                });

            modelBuilder.Entity("SMS.Data.ProjectRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EscalationLevelId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_ProjectRisk_CreatorId");

                    b.HasIndex(new[] { "ProjectId" }, "IX_ProjectRisk_ProjectId");

                    b.ToTable("ProjectRisk", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Sponsorship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PercentageCoverage")
                        .HasColumnType("int");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SponsorTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Sponsorship_CreatorId");

                    b.ToTable("Sponsorship", (string)null);
                });

            modelBuilder.Entity("SMS.Data.SponsorshipAcquittal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AmountDisbursed")
                        .HasColumnType("int");

                    b.Property<int?>("AmountUtilised")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("SponsorshipId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_SponsorshipAcquittal_CreatorId");

                    b.HasIndex(new[] { "CurrencyId" }, "IX_SponsorshipAcquittal_CurrencyId");

                    b.HasIndex(new[] { "SponsorshipId" }, "IX_SponsorshipAcquittal_SponsorshipId");

                    b.ToTable("SponsorshipAcquittal", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime");

                    b.Property<string>("EcNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QualificationId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Staff_UserId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("SMS.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllergieNotesJson")
                        .HasColumnType("text");

                    b.Property<int?>("BaptismStatusId")
                        .HasColumnType("int");

                    b.Property<string>("BirthEntryNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisabilityNotesJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EnrolmentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EnrolmentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<Guid?>("GuardianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsCatholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("VillageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassId" }, "IX_Student_ClassId");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Student_CreatorId");

                    b.HasIndex(new[] { "VillageId" }, "IX_Student_VillageId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("SMS.Data.StudentGuardian", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GuardianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Relationship")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GuardianId" }, "IX_StudentGuardian_GuardianId");

                    b.HasIndex(new[] { "StudentId" }, "IX_StudentGuardian_StudentId");

                    b.ToTable("StudentGuardian", (string)null);
                });

            modelBuilder.Entity("SMS.Data.StudentLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClosingBalance")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("OpeningBalance")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_StudentLedger_CreatorId");

                    b.HasIndex(new[] { "CurrencyId" }, "IX_StudentLedger_CurrencyId");

                    b.HasIndex(new[] { "StudentId" }, "IX_StudentLedger_StudentId");

                    b.HasIndex(new[] { "TermId" }, "IX_StudentLedger_TermId");

                    b.ToTable("StudentLedger", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Subject_CreatorId");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("SMS.Data.SyncChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClientTimeStamp")
                        .HasColumnType("datetime");

                    b.Property<string>("ConflictResolutionNotesJson")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("SyncStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SyncChange", (string)null);
                });

            modelBuilder.Entity("SMS.Data.TeacherSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StaffId" }, "IX_TeacherSubject_StaffId");

                    b.HasIndex(new[] { "SubjectId" }, "IX_TeacherSubject_SubjectId");

                    b.ToTable("TeacherSubject", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Term_CreatorId");

                    b.ToTable("Term", (string)null);
                });

            modelBuilder.Entity("SMS.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AuthRecoveryCodes")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AuthenticatorKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LockoutExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password_Hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("TwoFactorAuthEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SMS.Data.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("RightsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_UserGroup_CreatorId");

                    b.ToTable("UserGroup", (string)null);
                });

            modelBuilder.Entity("SMS.Data.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LoginDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LogoutDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserSession", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chief")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Headman")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Village_CreatorId");

                    b.ToTable("Village", (string)null);
                });

            modelBuilder.Entity("SMS.Data.Activity", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Activities")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Activity_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.Announcement", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Announcements")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Announcement_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.AuditLog", b =>
                {
                    b.HasOne("SMS.Data.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMS.Data.Class", b =>
                {
                    b.HasOne("SMS.Data.Staff", "ClassTeacher")
                        .WithMany("Classes")
                        .HasForeignKey("ClassTeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Class_Staff");

                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Classes")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Class_User");

                    b.HasOne("SMS.Data.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .IsRequired()
                        .HasConstraintName("FK_Class_Grade");

                    b.Navigation("ClassTeacher");

                    b.Navigation("Creator");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("SMS.Data.Competition", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Competitions")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Competition_User");

                    b.HasOne("SMS.Data.Term", "Term")
                        .WithMany("Competitions")
                        .HasForeignKey("TermId")
                        .IsRequired()
                        .HasConstraintName("FK_Competition_Term");

                    b.Navigation("Creator");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SMS.Data.Currency", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Currencies")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Currency_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.FeesStructure", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("FeesStructures")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_FeesStructure_User");

                    b.HasOne("SMS.Data.Currency", "Currency")
                        .WithMany("FeesStructures")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK_FeesStructure_FeesStructure");

                    b.Navigation("Creator");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("SMS.Data.Grade", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Grades")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Grade_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.Guardian", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Guardians")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Guardian_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.House", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Houses")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_House_User");

                    b.HasOne("SMS.Data.Staff", "Master")
                        .WithMany("Houses")
                        .HasForeignKey("MasterId")
                        .IsRequired()
                        .HasConstraintName("FK_House_Staff");

                    b.Navigation("Creator");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("SMS.Data.MassEvent", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("MassEvents")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_MassEvent_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.MassRoster", b =>
                {
                    b.HasOne("SMS.Data.MassEvent", "Mass")
                        .WithMany("MassRosters")
                        .HasForeignKey("MassId")
                        .IsRequired()
                        .HasConstraintName("FK_MassRoster_MassEvent");

                    b.HasOne("SMS.Data.Staff", "Staff")
                        .WithMany("MassRosters")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_MassRoster_Staff");

                    b.HasOne("SMS.Data.Student", "Student")
                        .WithMany("MassRosters")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_MassRoster_Student");

                    b.Navigation("Mass");

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SMS.Data.Payment", b =>
                {
                    b.HasOne("SMS.Data.Currency", "Currency")
                        .WithMany("Payments")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK_Payment_Currency");

                    b.HasOne("SMS.Data.User", "IdNavigation")
                        .WithOne("Payment")
                        .HasForeignKey("SMS.Data.Payment", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_User");

                    b.HasOne("SMS.Data.StudentLedger", "Ledger")
                        .WithMany("Payments")
                        .HasForeignKey("LedgerId")
                        .HasConstraintName("FK_Payment_StudentLedger");

                    b.Navigation("Currency");

                    b.Navigation("IdNavigation");

                    b.Navigation("Ledger");
                });

            modelBuilder.Entity("SMS.Data.Prefect", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Prefects")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Prefect_User");

                    b.HasOne("SMS.Data.Staff", "Nominator")
                        .WithMany("Prefects")
                        .HasForeignKey("NominatorId")
                        .HasConstraintName("FK_Prefect_Staff");

                    b.Navigation("Creator");

                    b.Navigation("Nominator");
                });

            modelBuilder.Entity("SMS.Data.Project", b =>
                {
                    b.HasOne("SMS.Data.Staff", "Creator")
                        .WithMany("Projects")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Project_Staff");

                    b.HasOne("SMS.Data.User", "CreatorNavigation")
                        .WithMany("Projects")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Project_User");

                    b.Navigation("Creator");

                    b.Navigation("CreatorNavigation");
                });

            modelBuilder.Entity("SMS.Data.ProjectMilestone", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("ProjectMilestones")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectMilestone_User");

                    b.HasOne("SMS.Data.Project", "Project")
                        .WithMany("ProjectMilestones")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectMilestone_Project");

                    b.Navigation("Creator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SMS.Data.ProjectRisk", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("ProjectRisks")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectRisk_User");

                    b.HasOne("SMS.Data.Project", "Project")
                        .WithMany("ProjectRisks")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectRisk_Project");

                    b.Navigation("Creator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SMS.Data.Sponsorship", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Sponsorships")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Sponsorship_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.SponsorshipAcquittal", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("SponsorshipAcquittals")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_SponsorshipAcquittal_User");

                    b.HasOne("SMS.Data.Currency", "Currency")
                        .WithMany("SponsorshipAcquittals")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK_SponsorshipAcquittal_Currency");

                    b.HasOne("SMS.Data.Sponsorship", "Sponsorship")
                        .WithMany("SponsorshipAcquittals")
                        .HasForeignKey("SponsorshipId")
                        .IsRequired()
                        .HasConstraintName("FK_SponsorshipAcquittal_Sponsorship");

                    b.Navigation("Creator");

                    b.Navigation("Currency");

                    b.Navigation("Sponsorship");
                });

            modelBuilder.Entity("SMS.Data.Staff", b =>
                {
                    b.HasOne("SMS.Data.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Staff_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMS.Data.Student", b =>
                {
                    b.HasOne("SMS.Data.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Student_Class");

                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Students")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_Student_User");

                    b.HasOne("SMS.Data.Village", "Village")
                        .WithMany("Students")
                        .HasForeignKey("VillageId")
                        .HasConstraintName("FK_Student_Village");

                    b.Navigation("Class");

                    b.Navigation("Creator");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("SMS.Data.StudentGuardian", b =>
                {
                    b.HasOne("SMS.Data.Guardian", "Guardian")
                        .WithMany("StudentGuardians")
                        .HasForeignKey("GuardianId")
                        .HasConstraintName("FK_StudentGuardian_Guardian");

                    b.HasOne("SMS.Data.Student", "Student")
                        .WithMany("StudentGuardians")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_StudentGuardian_Student");

                    b.Navigation("Guardian");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SMS.Data.StudentLedger", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("StudentLedgers")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("FK_StudentLedger_User");

                    b.HasOne("SMS.Data.Currency", "Currency")
                        .WithMany("StudentLedgers")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("FK_StudentLedger_Currency");

                    b.HasOne("SMS.Data.Student", "Student")
                        .WithMany("StudentLedgers")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentLedger_Student");

                    b.HasOne("SMS.Data.Term", "Term")
                        .WithMany("StudentLedgers")
                        .HasForeignKey("TermId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentLedger_Term");

                    b.Navigation("Creator");

                    b.Navigation("Currency");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SMS.Data.Subject", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Subjects")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Subject_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.TeacherSubject", b =>
                {
                    b.HasOne("SMS.Data.Staff", "Staff")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_TeacherSubject_Staff");

                    b.HasOne("SMS.Data.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_TeacherSubject_Subject");

                    b.Navigation("Staff");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SMS.Data.Term", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Terms")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Term_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.UserGroup", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("UserGroups")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_UserGroup_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.Village", b =>
                {
                    b.HasOne("SMS.Data.User", "Creator")
                        .WithMany("Villages")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("FK_Village_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SMS.Data.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SMS.Data.Currency", b =>
                {
                    b.Navigation("FeesStructures");

                    b.Navigation("Payments");

                    b.Navigation("SponsorshipAcquittals");

                    b.Navigation("StudentLedgers");
                });

            modelBuilder.Entity("SMS.Data.Grade", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("SMS.Data.Guardian", b =>
                {
                    b.Navigation("StudentGuardians");
                });

            modelBuilder.Entity("SMS.Data.MassEvent", b =>
                {
                    b.Navigation("MassRosters");
                });

            modelBuilder.Entity("SMS.Data.Project", b =>
                {
                    b.Navigation("ProjectMilestones");

                    b.Navigation("ProjectRisks");
                });

            modelBuilder.Entity("SMS.Data.Sponsorship", b =>
                {
                    b.Navigation("SponsorshipAcquittals");
                });

            modelBuilder.Entity("SMS.Data.Staff", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Houses");

                    b.Navigation("MassRosters");

                    b.Navigation("Prefects");

                    b.Navigation("Projects");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SMS.Data.Student", b =>
                {
                    b.Navigation("MassRosters");

                    b.Navigation("StudentGuardians");

                    b.Navigation("StudentLedgers");
                });

            modelBuilder.Entity("SMS.Data.StudentLedger", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SMS.Data.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("SMS.Data.Term", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("StudentLedgers");
                });

            modelBuilder.Entity("SMS.Data.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Announcements");

                    b.Navigation("AuditLogs");

                    b.Navigation("Classes");

                    b.Navigation("Competitions");

                    b.Navigation("Currencies");

                    b.Navigation("FeesStructures");

                    b.Navigation("Grades");

                    b.Navigation("Guardians");

                    b.Navigation("Houses");

                    b.Navigation("MassEvents");

                    b.Navigation("Payment");

                    b.Navigation("Prefects");

                    b.Navigation("ProjectMilestones");

                    b.Navigation("ProjectRisks");

                    b.Navigation("Projects");

                    b.Navigation("SponsorshipAcquittals");

                    b.Navigation("Sponsorships");

                    b.Navigation("Staff");

                    b.Navigation("StudentLedgers");

                    b.Navigation("Students");

                    b.Navigation("Subjects");

                    b.Navigation("Terms");

                    b.Navigation("UserGroups");

                    b.Navigation("Villages");
                });

            modelBuilder.Entity("SMS.Data.Village", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
